name: ShannonSevera
favicon: null
layout_spectrum: 0.551624775165692
typography_spectrum: 0.7686085517052561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.01811791746877134
  lightness: 0.7741195620037615
  saturation: 0.18820643052458763
  rhythmicContrast: 0.49330964498221874
purpose: []
